import { Categories, Data } from "@prisma/client";
import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Postsgroup from "./blogs/Postsgroup";
import { useRouter } from "next/router";

interface Props {
  data: Data[];
}

const MainPage: NextPage<Props> = ({ data }) => {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main>
        <Postsgroup data={data} />
      </main>
    </>
  );
};

export default MainPage;
