import { Data, PrismaClient } from "@prisma/client";
import { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Posts from "../components/blogs/Postsgroup";
//import styles from "../styles/Home.module.css";

interface Props {
  data: Data[];
}
const Home: NextPage<Props> = ({ data }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Posts data={data} />
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const prisma = new PrismaClient();
  const data: Data[] = await prisma.data.findMany({
    take: 10,
  });
  return {
    props: { data },
  };
};

export default Home;
